books_catalog/urls.py
from django.urls import path
from . import views

app_name = 'books_catalog'

urlpatterns = [
    path('', views.home, name='landing-page'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('profile/books', views.LoanedToUserListView.as_view(), name='profile-books'),

    path('profile/history', views.issue_history, name='issue-history'),

    path('librarian/borrowed', views.AllLoanedListView.as_view(), name='all-borrowed-books'),
    path('librarian/update-settings', views.update_library_settings, name='update-library-settings'),
    path('book/<int:pk>/edit', views.update_book, name='update-book'),
    path('books/add', views.add_book, name='add-book'),

    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/<uuid:pk>/borrow', views.borrow_book, name='borrow-book'),
    path('book/<uuid:pk>/return/', views.return_book, name='return-book'),

    path('feedback/submit', views.submit_portal_feedback, name='submit-portal-feedback'),
    path('feedback/view', views.view_portal_feedback, name='view-portal-feedback'),
    path('feedback/view/<int:feedback_id>/', views.feedback_detail, name='view-portal-feedback-detail'),  # Feedback details

    path('profile/favourites', views.favourite_list, name='favourite-list'),
    path('profile/favorites/add/<int:pk>/', views.add_favourite, name='add-favourite'),
    path('profile/favorites/remove/<int:pk>/', views.remove_favourite, name='remove-favourite'),

    path('search/', views.CatalogSearchView.as_view(), name='search'),
]

data_import/urls.py
from django.urls import path
from . import views

app_name = 'data_import'

urlpatterns = [
    path('accounts/librarian/import/', views.data_upload, name='data-upload'),
]

elibdeck/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('accounts/', include('users.urls')),
    path('', include('books_catalog.urls')),
    path('', include('data_import.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_dashboard, name='profile-page'),
    path('librarian/login/', views.LibrarianLoginView.as_view(), name='librarian-login'),
    path('profile/edit', views.edit_profile, name='edit-profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from uuid import uuid4
from books_catalog.models import BookInstance

class User(AbstractUser):
    is_librarian = models.BooleanField(default=False)
    psrn = models.CharField(
        max_length=255, default=uuid4, primary_key=True, editable=False, unique=True)
    room = models.CharField(max_length=10, default="No hostel.")

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from .models import User

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['room']  # Include other fields if necessary, e.g., email

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from allauth.account.views import LoginView
from django.contrib import messages
from .forms import EditUserForm


# Create your views here.
@login_required
def user_dashboard(request):
    """User page."""
    user = request.user

    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:profile-page')  # Redirect to avoid resubmission issues
    else:
        form = EditUserForm(instance=user)

    return render(request, 'users/dashboard.html', {'user': user})


class LibrarianLoginView(LoginView):
    template_name = 'users/librarian_login.html'


@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:profile-page')
    else:
        form = EditUserForm(instance=user)

    return render(request, 'users/edit_user.html', {'form': form})

users/templates/users/dashboard.html
{% extends 'generic.html' %}
{% block content %}
    <div class="container py-5">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                {% if not perms.books_catalog.can_mark_returned %}

                    <p class="text-muted mb-0">
                        {{ user.room }}
                    </p>
                {% else %}
                    <p class="text-muted mb-0">{{ user.psrn }}</p>
                {% endif %}
            </div>
            {% if not perms.books_catalog.can_mark_returned %}
                <a href="{% url 'users:edit-profile' %}" class="btn btn-outline-primary">
                    Edit
                </a>
            {% endif %}
        </div>

        <hr class="my-4">
        {% if not perms.books_catalog.can_mark_returned %}

            <h2>Reading Log</h2>
            <p class="mb-3">
                Books that you are
                <a href="{% url 'books_catalog:profile-books' %}" class="text-decoration-none">currently reading</a>,
                <a href="{% url 'books_catalog:issue-history' %}" class="text-decoration-none">have already read</a>,
                and
                <a href="/" class="text-decoration-none">liked the most</a>.
            </p>
        {% else %}
            <h2>Library Management</h2>
            <p class="mb-3">
                Add a
                <a href="{% url 'books_catalog:add-book' %}" class="text-decoration-none">book</a>,
                or import
                <a href="{% url 'data_import:data-upload' %}" class="text-decoration-none">multiple books</a>,
                or edit
                <a href="{% url 'books_catalog:update-library-settings' %}" class="text-decoration-none">library settings</a>.
            </p>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/dashboard_student.html
{% extends 'generic.html' %}

{% block content %}
  <div class="profile-container">
    <h1>Welcome, {{ user.first_name }}!</h1>
    <p>Email: {{ user.email }}</p>

    <table>
      <tr>
        <td>First Name:</td>
        <td>{{ user.first_name }}</td>
      </tr>
      <tr>
        <td>Last Name:</td>
        <td>{{ user.last_name }}</td>
      </tr>
      <tr>
        <td>Email:</td>
        <td>{{ user.email }}</td>
      </tr>
    </table>

    <a href="{% url 'books_catalog:profile-books' %}">Your borrowed books</a>
  </div>
{% endblock %}

users/templates/users/edit_user.html
{% extends 'generic.html' %}
{% block content %}
    <div class="container py-5">
        <form method="POST">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                    {% csrf_token %}
                    {% if not perms.books_catalog.can_mark_returned %}
                        {% for field in form %}
                            <tr>
                                <td><label for="{{ field.id_for_label }}">{{ field.label }}:</label></td>
                                <td>{{ field }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if not perms.books_catalog.can_mark_returned %}
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                {% endif %}
            </div>

            <hr class="my-4">

            <h2>Reading Log</h2>
            <p class="mb-3">
                Books that you are
                <a href="{% url 'books_catalog:profile-books' %}" class="text-decoration-none">currently reading</a>,
                <a href="{% url 'books_catalog:issue-history' %}" class="text-decoration-none">have already read</a>,
                and
                <a href="/" class="text-decoration-none">want to read</a>.
            </p>
        </form>
    </div>
{% endblock %}

users/templates/users/librarian_login.html
{% extends 'generic.html' %}

{% block content %}
<h2>Librarian Login</h2>
    <form method="post" action="{% url 'account_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}